### ISSUE TITLE
Japanese build in first release have "hojo" tables instead of primary Japanese tables

### ISSUE THREAD

**Issue by hanubeki** [TeamRizu/Texture-Font-Generator-2020-Squirrel#1]
Japanese build in first release seems to be built with `_TFG_JAPANESE_SUPPLEMENTAL`, which is options to generate JIS X 0212 "hojo" kanji and doesn't have JIS X 0201/0208/0213 which is primarily used for Japanese.

**Comment by Scraticus** [comment]
Fixed in v0.2 - thanks for the report!
